"""Agent request schemas."""

from typing import Any, Literal

from pydantic import BaseModel, Field


AgentIntent = Literal[
    "RECENT_SUMMARY",
    "HOMEWORK_DIAGNOSIS",
    "LESSON_FEEDBACK",
    "PARENT_REPLY",
]

AgentDataNeed = Literal[
    "student_profile",
    "recent_homeworks",
    "homework_detail",
    "wrong_question_stats",
    "recent_wrong_questions",
    "lesson_performance",
    "recent_lesson_performances",
    "class_students",
]


class AgentChatParams(BaseModel):
    """Optional frontend parameters for the MVP chat endpoint."""

    intent: AgentIntent = Field(default="RECENT_SUMMARY")
    time_range: str = Field(default="7d")
    subject: str = Field(default="数学")
    lesson_id: str | None = None
    tone: str = Field(default="温和")
    length: str = Field(default="标准版")
    parent_question: str | None = None


class AgentChatRequest(BaseModel):
    """Request body for POST /agent/mvp/chat."""

    conversation_id: str | None = None
    teacher_id: str = Field(default="")
    student_id: str = Field(default="")
    message: str = Field(default="")
    scene: str = Field(default="student_detail")
    params: AgentChatParams = Field(default_factory=AgentChatParams)
    context: dict[str, Any] = Field(default_factory=dict)


class AgentPlanStep(BaseModel):
    """One internal execution-plan step."""

    step_id: str
    goal: str
    data_needs: list[AgentDataNeed] = Field(default_factory=list)
    output_requirements: list[str] = Field(default_factory=list)


class AgentExecutionPlan(BaseModel):
    """Internal plan generated by the Planner. Never returned to the frontend."""

    intent: AgentIntent
    task_goal: str
    steps: list[AgentPlanStep] = Field(default_factory=list)
    data_needs: list[AgentDataNeed] = Field(default_factory=list)
    response_requirements: list[str] = Field(default_factory=list)
    planner_reason: str = ""
